### ISSUE TITLE
Add export of rgl scenes to Amira

### ISSUE THREAD

**Issue by ajdm** [jefferis/nat#155]
As mentioned in [flycircuit#27](https://github.com/jefferis/flycircuit/pull/27).

**Comment by jefferis** [comment]
See the new [nat.amira](https://github.com/jefferis/nat.amira) package which offers some basic functionality to export traces into a hierarchy suitable for display in Amira.

**Comment by jefferis** [comment]
note also that Amira can import vrml

**Comment by jefferis** [comment]
We will not provide this functionality in nat. It is possible that we may consider future work in the **nat.amira** package to do this.
