### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ajdm** [jefferis/nat#158]
The new package [testCoverage](https://github.com/MangoTheCat/testCoverage) (with a few modifications) claims that the tests currently cover 54 % of the code. This is a bit of an underestimate, as a lot of the things that are not covered directly lead to `stop()` calls, and a lot of tests don't actually run properly, but, even so, it seems useful to use these results to guide where extra tests should be added.

**Comment by jefferis** [comment]
Have now added support for https://github.com/jimhester/covr.

**Comment by jefferis** [comment]
Have made a start on this on branch https://github.com/jefferis/nat/tree/fix/improve-test-coverage (merged). I will probably continue to work on this periodically as I picked up a number of bugs when completing the test coverage for a few files in the commits https://github.com/jefferis/nat/compare/d4f6f94c6...af05c62

**Comment by jefferis** [comment]
I'm going to closes this now that coverage has reached 92%.
