### ISSUE TITLE
Error installing nat

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/nat#298]
Error installing nat on some machines (Kathi's). Says that the function 'bfs' is not imported from the namescpae igraph. But the newest igraph seems to still have bfs...

**Comment by ajdm** [comment]
Hi Alex,

What's the output of
```
R.Version()
```
and
```
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
print(ip, row.names=FALSE)
```
?

**Comment by alexanderbates** [comment]
Sorry, the system didn't have the newest version of R, that was the problem. Thank you for pointing me in the right direction. Works fine now.

**Comment by jefferis** [comment]
Which version did it have? We might make a version restriction in the package DESCRIPTION.

**Comment by alexanderbates** [comment]
R version 3.1.2 (2014-10-31). I have version 3.2.2 and it all works fine.

**Comment by jefferis** [comment]
Just as a note, the specific problem is that on older version of macosx with older versions of R, igraph >1.0 is not available and nat now depends on that. The simple thing to is to put a version requirement on igraph. However compiling it is a bit of a pain and I don't think I'm using any functionality that is specific to v1 of the library. So I could change `bfs` to `graph.bfs` (the old name). However there may be some other  things that are still 1.0 specific by chance.
