### ISSUE TITLE
Install CMTK on Windows

### ISSUE THREAD

**Issue by zcbtgx9** [jefferis/nat#314]
I followed the intruction on https://github.com/jefferis/nat/tree/dev#cmtknat-on-windows. But when I run the test code, error occurs as below: 

$ cmtk.dof2mat(version = TRUE)
-bash: syntax error near unexpected token `version'

I'm using Windows 10. Would this be the problem? 
Cheers

**Comment by jefferis** [comment]
A couple things to check.

Are you using the GitHub or CRAN version of the package? Maybe you could report the output of devtools::session_info()

What does cmtk.bindir() return?

Thanks, Greg.

**Comment by zcbtgx9** [comment]
Hi Greg,

I'm using the package from : http://www.nitrc.org/frs/?group_id=212

I get no output with either command :( 
$ devtools::session_info()
>
>
>
>
>
>
>
>


$ cmtk.bindir()
>
>
>
>
>
>
>
>
>
>

**Comment by jefferis** [comment]
Those are both R commands that you need to run in an R session. It looks you are running them in the shell.

**Comment by zcbtgx9** [comment]
Ah! I thought they were for cygwin! Here's what I got in R: 
 devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-10-16                  

Packages -----------------------------------------------------------------------
 package  * version date       source        
 curl       2.1     2016-09-22 CRAN (R 3.3.1)
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest     0.6.10  2016-08-02 CRAN (R 3.3.1)
 git2r      0.15.0  2016-05-11 CRAN (R 3.3.1)
 httr       1.2.1   2016-07-03 CRAN (R 3.3.1)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.1)
 R6         2.2.0   2016-10-05 CRAN (R 3.3.1)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.1)

cmtk.bindir()
Error: could not find function "cmtk.bindir"

**Comment by jefferis** [comment]
For the second command you need to do

```r
library(nat)
cmtk.bindir()
```

**Comment by jefferis** [comment]
But as far as I can tell you haven't actually done the R part of the install.

**Comment by zcbtgx9** [comment]
I run the code on the website https://github.com/jefferis/nat/tree/dev#cmtknat-on-windows. What else I need to do to install cmtk on R? 
 
Btw, 
> library(nat)
> cmtk.bindir()
NULL

**Comment by jefferis** [comment]
Sorry, could you rerun session_info after loading nat, so I can see what version you have installed?

```r
library(nat)
devtools::session_info()
```

Also after that can you do

```
cmtk.dof2mat(version = TRUE)
```
in your R session.

**Comment by zcbtgx9** [comment]
This is what I get: 

> cmtk.dof2mat(version = TRUE)
Error in cmtk.bindir(check = TRUE) : 
  Cannot find CMTK. Please install from http://www.nitrc.org/projects/cmtk and make sure that it is your path!
>

**Comment by jefferis** [comment]
Can you run this:

```
library(nat)
devtools::session_info()
```
to confirm which version of nat you have installed.

And in addition can you try to find out exactly where CMTK in installed on your system. It may be that it is in a different location from my limited test systems. In the cygwin terminal I am expecting it to be installed at:

`C:\\cygwin64\\usr\\local\\lib\\cmtk\\bin`

If it is not there you will have to find the corresponding location and do something like:
```r
op=options(nat.cmtk.bindir='C:\\cygwin64\\usr\\local\\lib\\cmtk\\bin')
```
replacing with the correct path.

**Comment by zcbtgx9** [comment]
> library(nat)
> devtools::session_info()

Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-10-16                  

Packages -----------------------------------------------------------------------
 package     * version date       source                       
 codetools     0.2-14  2015-07-15 CRAN (R 3.3.1)               
 curl          2.1     2016-09-22 CRAN (R 3.3.1)               
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.1)               
 digest        0.6.10  2016-08-02 CRAN (R 3.3.1)               
 filehash      2.3     2015-08-16 CRAN (R 3.3.1)               
 git2r         0.15.0  2016-05-11 CRAN (R 3.3.1)               
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.1)               
 htmlwidgets   0.7     2016-08-02 CRAN (R 3.3.1)               
 httpuv        1.3.3   2015-08-04 CRAN (R 3.3.1)               
 httr          1.2.1   2016-07-03 CRAN (R 3.3.1)               
 igraph        1.0.1   2015-06-26 CRAN (R 3.3.0)               
 jsonlite      1.1     2016-09-14 CRAN (R 3.3.1)               
 knitr         1.14    2016-08-13 CRAN (R 3.3.1)               
 magrittr      1.5     2014-11-22 CRAN (R 3.3.1)               
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.1)               
 mime          0.5     2016-07-07 CRAN (R 3.3.1)               
 nabor         0.4.6   2015-05-28 CRAN (R 3.3.1)               
 nat         * 1.7.2   2016-10-16 Github (jefferis/nat@316c2a4)
 nat.utils     0.5.1   2015-07-04 CRAN (R 3.3.1)               
 R6            2.2.0   2016-10-05 CRAN (R 3.3.1)               
 Rcpp          0.12.7  2016-09-05 CRAN (R 3.3.1)               
 rgl         * 0.96.0  2016-08-25 CRAN (R 3.3.1)               
 rstudioapi    0.6     2016-06-27 CRAN (R 3.3.1)               
 shiny         0.14.1  2016-10-05 CRAN (R 3.3.1)               
 withr         1.0.2   2016-06-20 CRAN (R 3.3.1)               
 xtable        1.8-2   2016-02-05 CRAN (R 3.3.1)               
 yaml          2.1.13  2014-06-12 CRAN (R 3.3.1)       

I can see the cmtk\bin folder. I assume it's installed there? 

In any case, when I run:
> op=options(nat.cmtk.bindir='C:\\cygwin64\\usr\\local\\lib\\cmtk\\bin')
> cmtk.dof2mat(version = TRUE)
Error in cmtk.bindir(check = TRUE) : 
  cmtk is _not_ installed at:C:\cygwin64\usr\local\lib\cmtk\bin
Please check value of options('nat.cmtk.bindir')

**Comment by jefferis** [comment]
That version of nat (1.7.2) is old. You need to install the latest version using the instructions in the readme. I recommend using devtools to install from GitHub.

**Comment by zcbtgx9** [comment]
You know what, I changed my R working directory to C:\cygwin64\usr\local\lib\cmtk\bin, and now, I get cmtk.dof2mat(version = TRUE)
[1] "3.3.1"

Thanks for helping me!

**Comment by jefferis** [comment]
> You know what, I changed my R working directory to C:\cygwin64\usr\local\lib\cmtk\bin, and now, I get cmtk.dof2mat(version = TRUE)

That's great and I hadn't thought of suggesting it, but it will probably not work in all situations. Just to wrap up:

1. From the `session_info` output that you printed above you had nat v1.7.2 installed but at least version [nat v1.8.5](https://github.com/jefferis/nat/releases/tag/v1.8.5) is required for Windows cygwin support. My impression is that you still haven't upgraded nat and that if you do 

2. The error message in your first post suggests that you were pasting R code into the cygwin bash shell.

I have amended the README instructions to make this clear. If you have any comments on the readability of [the changes I made](https://github.com/jefferis/nat/compare/d3119509748daed8f7f02bf634611ccc556c5342...master) I would be happy to have them. Thanks again for your interest in nat.

**Comment by zcbtgx9** [comment]
Hi Jefferis,

I find the README easier to follow now. I have updated my nat now, but if don't change my directory, here's what I have: 

library(nat)
cmtk.dof2mat(version = TRUE)
Error in cmtk.bindir(check = TRUE) : 
  Cannot find CMTK. Please install from http://www.nitrc.org/projects/cmtk and make sure that it is your path!


 devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-10-18                  

Packages -----------------------------------------------------------------------
 package     * version date       source        
 codetools     0.2-14  2015-07-15 CRAN (R 3.3.1)
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest        0.6.10  2016-08-02 CRAN (R 3.3.1)
 filehash      2.3     2015-08-16 CRAN (R 3.3.1)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.1)
 htmlwidgets   0.7     2016-08-02 CRAN (R 3.3.1)
 httpuv        1.3.3   2015-08-04 CRAN (R 3.3.1)
 igraph        1.0.1   2015-06-26 CRAN (R 3.3.0)
 jsonlite      1.1     2016-09-14 CRAN (R 3.3.1)
 knitr         1.14    2016-08-13 CRAN (R 3.3.1)
 magrittr      1.5     2014-11-22 CRAN (R 3.3.1)
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.1)
 mime          0.5     2016-07-07 CRAN (R 3.3.1)
 nabor         0.4.6   2015-05-28 CRAN (R 3.3.1)
 nat         * 1.8.4   2016-07-18 CRAN (R 3.3.1)
 nat.utils     0.5.1   2015-07-04 CRAN (R 3.3.1)
 R6            2.2.0   2016-10-05 CRAN (R 3.3.1)
 Rcpp          0.12.7  2016-09-05 CRAN (R 3.3.1)
 rgl         * 0.96.0  2016-08-25 CRAN (R 3.3.1)
 rstudioapi    0.6     2016-06-27 CRAN (R 3.3.1)
 shiny         0.14.1  2016-10-05 CRAN (R 3.3.1)
 withr         1.0.2   2016-06-20 CRAN (R 3.3.1)
 xtable        1.8-2   2016-02-05 CRAN (R 3.3.1)
 yaml          2.1.13  2014-06-12 CRAN (R 3.3.1)

**Comment by jefferis** [comment]
Thanks for checking readme.

Re the persistent error, you have updated to v1.8.4 from CRAN but you need >=v1.8.5 which is only available directly from github. You can do this 

```r
devtools::install_github("jefferis/nat")
```

to update to the development version as mentioned in the README.

**Comment by zcbtgx9** [comment]
Yup. That's right. Thanks for pointing that out. It works now without changing directory. 

btw, you may want to add in README that to copy the files in cygwin, need to run it as administrator, and then:
cp C:/cygwin64/bin/cyg*.dll  C:/Windows/System32/
