### ISSUE TITLE
Speed up strahler_order

### ISSUE THREAD

**Issue by jefferis** [jefferis/nat#335]
Looks like there are two places that are a bit slow

```
 n=neighborhood(s, 1, mode='out')
```
and
 
```
so_segends=so_red_nodes[match(segends, svids)]
```

The latter (which takes 2-3s for a 60k node neuron like mvp2, is slow because it assumes svids is unsorted (it should actually be sorted). If we could do it in one pass it would take no time at all (<1ms).

**Comment by jefferis** [comment]
`neighborhood` can be made much faster by setting

```
igraph_options(return.vs.es=FALSE)
```
setting this temporarily and then resetting the old value is a bit clunky but seems to be the best thing I can come up with.

**Comment by jefferis** [comment]
closed by ed06211d961b3d88492b969c2cba747d8b1a8b87

**Comment by jefferis** [comment]
Turns out I am hitting what it looks like an igraph bug. 

```
igraph_options(return.vs.es=FALSE)
```
using this inside a package gives 

```
Error in assign(".igraph.pars", current, envir = env) : 
  cannot change value of locked binding for '.igraph.pars'
```

**Comment by koheiw** [comment]
@jefferis, I am facing the same error in our package:
https://github.com/kbenoit/quanteda/blob/dev-network/R/textplot_network.R

Did you find a solution or workaround?

**Comment by jefferis** [comment]
Hi @koheiw, I'm afraid I did not and I received no response from the igraph mailing list either https://lists.nongnu.org/archive/html/igraph-help/2017-03/msg00002.html. The thing is that this bug is fixed in the development version of igraph. Therefore the obvious thing to do is to use that. I do not because it imposes a requirement on compiling the igraph library which is a bit heavy for some of users. Best would be if the igraph team made a new CRAN release, but I think this is quite a big job for them. Still I think it could be a good idea for you to write the mailing list a follow up to my message.

**Comment by koheiw** [comment]
@jefferis thank you, very helpful. I should follow up on the mailing list.

**Comment by koheiw** [comment]
Just to let you know that igraph seems to work when `plot.igraph()` is used instead of the generic `plot()`. Please try in your package.

**Comment by jefferis** [comment]
Since igraph 1.1 the igraph options mechanism works fine. Have decided just to turn off vs.es for the whole nat package. Now the MVP2 example drops from 12s to 0.6s i.e. 20x faster.
