### ISSUE TITLE
PlotSubTrees option for plot.neuron

### ISSUE THREAD

**Issue by zhihaozheng** [jefferis/nat#339]
Same as `plot3d.neuron`. So basically insert `if(PlotSubTrees && !is.null(x$SubTrees)) x$SegList=unlist(x$SubTrees,recursive=FALSE)` somewhere in `plot.neuron`. I can put it in and submit a pull request.

**Comment by jefferis** [comment]
Good idea! Do you want to make a PR? Thanks, Greg.

**Comment by zhihaozheng** [comment]
Sure, will do later tonight.

**Comment by jefferis** [comment]
Closed by #340
