### ISSUE TITLE
write.vtk produces polyline objects unable to be assembled by VTK

### ISSUE THREAD

**Issue by a-r-j** [jefferis/nat#362]
Tracked down my issue with deformetrica. `nat::write.vtk() `appears to write `.vtk` files incorrectly, resulting in the following error when assembling poly line objects in VTK's `vtkPolyData()` (https://github.com/Kitware/VTK/blob/master/Common/DataModel/vtkPolyData.cxx):

`Building VTK_LINE 4 with only one point, but VTK_LINE needs at least two points. Check the input. (Line 993).` 

Alex's VTK I/o functions in deformetricar appear to work.

**Comment by jefferis** [comment]
Hi @a-r-j thanks for the big report. Was there a reason why you closed it?
