### ISSUE TITLE
Add note to Cygwin installation

### ISSUE THREAD

**Issue by mmc46** [jefferis/nat#368]
On the installation page

http://jefferis.github.io/nat/articles/Installation.html#cmtknat-on-windows

Can an extra line be added after 
"Start a Cygwin terminal and issue the following command tar -xvf CMTK-3.3.1-CYGWIN-x86_64.tar.gz to extract CMTK to the cygwin folder." 

to explain that when opening the terminal, it will be in the home directory. So the user will need to navigate to the right directory using `cd ../../..` (not sure if this path applies to everyone) before using the command `tar -xvf CMTK-3.3.1-CYGWIN-x86_64.tar.gz`

**Comment by jefferis** [comment]
Thanks! Can you edit https://github.com/jefferis/nat/edit/master/vignettes/Installation.Rmd to add the missing instructions. I think it should `cd /` to get there.

**Comment by jefferis** [comment]
Closed by #369
